spring.application.name=Project_web
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=student_1;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
